export default {
  EOF: "EOF",
  STRING: "STRING",
  INT: "INT",
  FLOAT: "FLOAT",
  KEYWORD: "KEYWORD",
  IDENTIFIER: "IDENTIFIER",
  DOT: "DOT",
  EQUALS: "EQUALS",
  NOT_EQUALS: "NOT_EQUALS",
  NOT: "NOT",
  DEFINE: "DEFINE",
  NEW_LINE: "NEW_LINE"
}